// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD-zXboYvZBGN7xEmkHiqFyT40L_NOZQw',
    appId: '1:199022085697:web:2cc879d5aa555d65e068c0',
    messagingSenderId: '199022085697',
    projectId: 'tech-convene',
    authDomain: 'tech-convene.firebaseapp.com',
    storageBucket: 'tech-convene.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmspQnni8785T0g_FPJ6mDiTwWoW5DbXk',
    appId: '1:199022085697:android:739640d844b80be6e068c0',
    messagingSenderId: '199022085697',
    projectId: 'tech-convene',
    storageBucket: 'tech-convene.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzto6EziPT0WnTkVyqG_lH9x51jmMan6o',
    appId: '1:199022085697:ios:215c4be6e8fe5f36e068c0',
    messagingSenderId: '199022085697',
    projectId: 'tech-convene',
    storageBucket: 'tech-convene.appspot.com',
    androidClientId: '199022085697-rr5rrob4m2o78msihe9ogipinobi1ouj.apps.googleusercontent.com',
    iosClientId: '199022085697-6dtsvnbd1mshlcbia26trl62vpqj3ara.apps.googleusercontent.com',
    iosBundleId: 'com.dhenterrprises.techconvene',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzto6EziPT0WnTkVyqG_lH9x51jmMan6o',
    appId: '1:199022085697:ios:215c4be6e8fe5f36e068c0',
    messagingSenderId: '199022085697',
    projectId: 'tech-convene',
    storageBucket: 'tech-convene.appspot.com',
    androidClientId: '199022085697-rr5rrob4m2o78msihe9ogipinobi1ouj.apps.googleusercontent.com',
    iosClientId: '199022085697-6dtsvnbd1mshlcbia26trl62vpqj3ara.apps.googleusercontent.com',
    iosBundleId: 'com.dhenterrprises.techconvene',
  );
}
